// Code generated by ogen, DO NOT EDIT.
package api

type V1AdminCategoriesGetRes interface {
	v1AdminCategoriesGetRes()
}

type V1AdminCategoriesIDDeleteRes interface {
	v1AdminCategoriesIDDeleteRes()
}

type V1AdminCategoriesIDPutRes interface {
	v1AdminCategoriesIDPutRes()
}

type V1AdminCategoriesPostRes interface {
	v1AdminCategoriesPostRes()
}
