// Code generated by ogen, DO NOT EDIT.
package api

type V1AdminCategoriesDeleteRes interface {
	v1AdminCategoriesDeleteRes()
}

type V1AdminCategoriesGetRes interface {
	v1AdminCategoriesGetRes()
}

type V1AdminCategoriesPostRes interface {
	v1AdminCategoriesPostRes()
}

type V1AdminCategoriesPutRes interface {
	v1AdminCategoriesPutRes()
}
