services:
  pg_question:
    restart: always
    container_name: pg_question
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=uo_question
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uo_question"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local