openapi: 3.0.3
info:
  title: Uoffer Question API
  description: question api
  version: 1.0.0
servers:
  - description: local
    url: /
  - description: dev
    url: /
paths:
  /v1/admin/categories:
    get:
      tags:
        - categories
      summary: Получить все категории
      description: Возвращает список всех категорий с возможностью пагинации
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          description: Номер страницы для пагинации
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        - name: per_page
          in: query
          description: Количество категорий на странице
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
      responses:
        '200':
          description: Список категорий успешно получен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/categoriesResp'
        '400':
          description: Некорректные параметры запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Категории не найдены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        default:
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      tags:
        - categories
      summary: Добавить категорию
      description: Создает новую категорию
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoryPost'
      responses:
        '201':
          description: Категория успешно добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
        '400':
          description: Некорректные данные.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '409':
          description: Категория с таким названием уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        default:
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /v1/admin/categories/{categoryID}:
    put:
      tags:
        - categories
      summary: Обновить категорию
      description: Обновляет категорию
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: categoryID
          schema:
            type: integer
            minimum: 1
          required: true
          description: Уникальный идентификатор категории
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/categoryPut'
      responses:
        '200':
          description: Категория успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/category'
        '400':
          description: Некорректные данные.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Категория не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '409':
          description: Категория с таким названием уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        default:
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      tags:
        - categories
      summary: Удаление категории
      description: Удаляет категорию по ее уникальному идентификатору.
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: categoryID
          schema:
            type: integer
            minimum: 1
          required: true
          description: Уникальный идентификатор категории
      responses:
        '204':
          description: Категория успешно удалена
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Категория не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '409':
          description: Нельзя удалить категорию, так как на нее ссылаются должности
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        default:
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    error:
      type: object
      required:
        - message
        - details
      properties:
        message:
          type: string
          description: error message
          example: Invalid
        details:
          type: object
          additionalProperties: true
    category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Books
        public:
          type: boolean
          example: true
      required:
        - id
        - title
        - public
    categoriesResp:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/category'
        page:
          type: integer
          example: 0
        pages:
          type: integer
          example: 13
        per_page:
          type: integer
          example: 1
      required:
        - data
        - page
        - pages
        - per_page
    categoryPost:
      type: object
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 50
          example: Books
        public:
          type: boolean
          example: true
      required:
        - title
        - public
    categoryPut:
      type: object
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 50
          example: Books
        public:
          type: boolean
          example: true
