openapi: 3.0.3
servers:
  - description: local
    url: /
  - description: dev
    url: /
info:
  title: Uoffer Question API
  description: question api
  version: 1.0.0

paths:
  /v1/categories:
    $ref: "./v1/paths/category/category.yml"        

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT