openapi: 3.0.3
servers:
  - description: local
    url: /
  - description: dev
    url: /
info:
  title: Uoffer Question API
  description: question api
  version: 1.0.0
  
paths:
  /v1/categories:
  #   get:
  #     summary: Получение всех категорий
  #     description: Возвращает список всех категорий
  #     security:
  #       - bearerAuth: []
  #     responses:
  #       '200':
  #         description: Успешно
  #         content:
  #           application/json:
  #             schema:
  #               # type: object
  #               $ref: '#/components/schemas/Category'
  #       '401':
  #         description: Неавторизованный доступ
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       '404':
  #         description: Категории не найдены.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       default:
  #         description: Неизвестная ошибка
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'

    post:
      summary: Добавить категорию
      description: Создает новую категорию
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Категория успешно добавлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Некорректные данные.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Категория с таким названием уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Неавторизованный доступ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Неизвестная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # /v1/categories/{id}:
  #   delete:
  #     summary: Удалить категорию
  #     description: Удаляет категорию по её ID
  #     security:
  #       - bearerAuth: []
  #     parameters:
  #       - in: path
  #         name: id
  #         required: true
  #         schema:
  #           type: integer
  #         description: ID категории
  #     responses:
  #       '204':
  #         description: Категория успешно удалена
  #       '401':
  #         description: Неавторизованный доступ
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       '404':
  #         description: Категория не найдена
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       default:
  #         description: Неизвестная ошибка
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'

  #   put:
  #     summary: Обновить категорию
  #     description: Обновляет данные категории по её ID
  #     security:
  #       - bearerAuth: []
  #     parameters:
  #       - in: path
  #         name: id
  #         required: true
  #         schema:
  #           type: integer
  #         description: ID категории
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/CategoryInput'
  #     responses:
  #       '200':
  #         description: Категория успешно обновлена
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Category'
  #       '400':
  #         description: Некорректные данные.
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       '404':
  #         description: Категория не найдена
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       '401':
  #         description: Неавторизованный доступ
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'
  #       default:
  #         description: Неизвестная ошибка
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Books"
      required:
        - id
        - title

    CategoryInput:
      type: object
      properties:
        title:
          type: string
          maxLength: 50
          example: "Books"
      required:
        - title

    Error:
      type: object
      required:
        - message
        - details
      properties:
        message:
          type: string
          description: error message
          example: "Invalid"
        details:
          type: object
          additionalProperties: true